CREATE TABLE IF NOT EXISTS Employee(
	EmployeeID INTEGER PRIMARY KEY AUTOINCREMENT,
	FirstName TEXT NOT NULL,
	MiddleName TEXT,
	LastName TEXT NOT NULL,
	EmployeeGroup TEXT,
	UNIQUE(FirstName, MiddleName, LastName)
);

CREATE TABLE IF NOT EXISTS PayPeriod(
	PayPeriodID INTEGER PRIMARY KEY AUTOINCREMENT,
	EmployeeID INTEGER NOT NULL,
	StartDate TEXT NOT NULL,
	EndDate TEXT NOT NULL,
	UNIQUE(EmployeeID, StartDate, EndDate),
	FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS WorkEntry(
	WorkEntryID INTEGER PRIMARY KEY AUTOINCREMENT,
	PayPeriodID INTEGER NOT NULL,
	WorkDate TEXT NOT NULL,
	Hours REAL NOT NULL CHECK(Hours >= 0.0),
	UNIQUE(PayPeriodID, WorkDate),
	FOREIGN KEY (PayPeriodID) REFERENCES PayPeriod(PayPeriodID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PayPeriodComment (
	CommentID INTEGER PRIMARY KEY AUTOINCREMENT,
	PayPeriodID INTEGER NOT NULL,
	EmployeeID INTEGER NOT NULL,
	WorkDate TEXT NOT NULL,
	PunchInComment TEXT NOT NULL DEFAULT '',
	PunchOutComment TEXT NOT NULL DEFAULT '',
	SpecialPayComment TEXT NOT NULL DEFAULT '',
	FOREIGN KEY (PayPeriodID) REFERENCES PayPeriod(PayPeriodID) ON DELETE CASCADE,
	FOREIGN KEY (EmployeeID) REFERENCES Employee(EmployeeID) ON DELETE CASCADE,
	UNIQUE(PunchInComment, PunchOutComment, SpecialPayComment)
);

CREATE TABLE IF NOT EXISTS Meta(
	Key TEXT PRIMARY KEY,
	Value TEXT
);

INSERT OR REPLACE INTO Meta (Key, Value)
VALUES ('SchemaVersion', '1.0.0');
