import re


class Parser:
    '''
        Utility class to parse reports generated by Time Trax
        time clocks.

        This class will have to be updated if you use a different
        time clock.
    '''

    def __init__(self, log_level):
        self.log_level = log_level

    def hrsFormatter(arr):
        if arr == "":
            return 0

        else:
            arr = arr.split(":")
            stack = [float(i) for i in arr]

            if stack[1] == 15:
                stack[1] = .25
            elif stack[1] == 30:
                stack[1] = .50
            elif stack[1] == 45:
                stack[1] = .75

            return stack[0] + stack[1]

    def xlsParser(sheet,
                  mincolx, minrowy,
                  maxcolx, maxrowy,
                  target, xbuff, ybuff) -> []:
        answer = []

        for row in range(minrowy, maxrowy):
            for col in range(mincolx, maxcolx):
                curr = sheet.cell_value(row, col)
                if xbuff is not None:
                    if re.search(pattern=target, string=curr) is not None:
                        col += xbuff
                        answer.append(sheet.cell_value(row, col))
                        answer.append([row, col])
                        col -= xbuff
                elif ybuff is not None:
                    if re.search(pattern=target, string=curr) is not None:
                        row += ybuff
                        answer.append(sheet.cell_value(row, col))
                        answer.append([row, col])
                        row -= ybuff
                else:
                    if re.search(pattern=target, string=curr) is not None:
                        answer.append(curr)
                        answer.append([row, col])
        return answer
